### ISSUE TITLE
Docktor Monitoring Stack

### ISSUE THREAD

**Issue by yesnault** [docktor/docktor#64]
New entry in admin : Monitoring Stack
- [ ] Deploy one or many cAdvisor (can be modify) on DOCKTOR group.
- [ ] Deploy one or many influxDB (can be modify) on DOCKTOR group.
- [ ] Deploy one or many Docktor/Riemann (can be modify by user) on DOCKTOR group, with params from influxDB  automatically filled
- [ ] Deploy one or many Docktor/goryCadvisor (can be modify by user) on DOCKTOR group, with params from  influxDB and Riemann automatically filled
- [ ] Deploy one or many Docktor/Grafana (can be modify by user) on DOCKTOR group, with params from influxDB  automatically filled

--> using images from https://github.com/docktor/dockerfiles
