### ISSUE TITLE
Update a service

### ISSUE THREAD

**Issue by yesnault** [docktor/docktor#9]
- [ ] update an existing image : display how many groups are using this image 
- [x] add a new image : allow duplicate an existing image
- [ ] if all params are the same or with default value of an existing deployed service, allow user (role user) to upgrade a service to a new version
- [ ] allow an admin to upgrade an existing image (can update all params)
